version: 2
jobs:
  build-site:
    docker:
      - image: circleci/node:8.11.3 # NodeLTS as of 06/2018
    environment:
      NODE_ENV: "production" # Won't install anything from devDependencies.
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: 
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules/
      - run: 
          name: Build adamzerella.com
          command: yarn build
      - persist_to_workspace:
          root: ~/project # /home/circleci/project
          paths:
            - ./build
  deploy-site:
    docker:
      - image: circleci/ubuntu-server:latest
    steps:
      - attach_workspace:
          at: ~/project # /home/root/project
      - run:
          name: Deploying to AWS Bitnami Apache
          command: scp -r ./build $LS_USERNAME@$LS_SERVER:$LS_PATH
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-site:
          filters:
            branches:
              only:
                - master
      - deploy-site:
          requires:
            - build-site